"""
main.py — FastAPI Server Entry Point.

Run this file to start the API server:
    python main.py

The server starts at: http://localhost:8000
API docs (Swagger UI): http://localhost:8000/docs
API docs (ReDoc):      http://localhost:8000/redoc

AVAILABLE ENDPOINTS:
  GET  /          → Health check (returns {"status": "ok"})       [no auth]
  GET  /health    → Health check (Cloud Run compatible alias)      [no auth]
  POST /research  → Submit a research question, get back a report  [requires auth]
  GET  /research/history          → Get your research history      [requires auth]
  GET  /research/{research_id}    → Get a specific research result [requires auth]
"""

import os
import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# ── Import and validate API keys BEFORE anything else ────────────────────────
# If any key is missing, this will raise a clear error and stop the server.
# The noqa comment suppresses the "imported but unused" warning — the import
# itself triggers the validation as a side effect.
from app.config import (  # noqa: F401
    HF_TOKEN,
    GOOGLE_API_KEY,
    GOOGLE_API_KEY2,
    GROQ_API_KEY,
    TAVILY_API_KEY,
    FIREBASE_PROJECT_ID,
    FIREBASE_CLIENT_EMAIL,
    FIREBASE_PRIVATE_KEY,
    FRONTEND_URL,
)

# ── Import routes ─────────────────────────────────────────────────────────────
from app.routes.research import router as research_router
from app.routes.history import router as history_router

# ── Initialize Firebase Admin SDK ─────────────────────────────────────────────
# This MUST happen before any route that uses Firebase Auth or Firestore.
# We import and call this once at startup.
from app.services.firebase import initialize_firebase
initialize_firebase()


# ── Create the FastAPI app ────────────────────────────────────────────────────

app = FastAPI(
    title="Deep Research Agent API",
    description=(
        "A multi-agent research pipeline powered by LangGraph.\n\n"
        "Submit a question and receive a detailed markdown report "
        "generated by specialized AI agents:\n"
        "- **Planner** → breaks question into 3 sub-tasks\n"
        "- **3 Researchers** → gather evidence in parallel (with web search)\n"
        "- **Collector** → organizes findings\n"
        "- **Critic** → quality-checks the evidence\n"
        "- **Report Writer** → writes the final report\n"
        "- **Image Agent** → adds technical diagrams\n"
        "- **File Saver** → saves the report as a .md file\n\n"
        "**Authentication:** All research endpoints require a Firebase ID token.\n"
        "Click the 🔒 Authorize button above and paste your token to test."
    ),
    version="2.0.0",
)


# ── CORS Middleware ───────────────────────────────────────────────────────────
# CORS = Cross-Origin Resource Sharing.
# Without this, browsers block requests from your frontend to this API.
#
# HOW IT WORKS:
#   - In DEVELOPMENT: your frontend runs on http://localhost:5173 (Vite)
#     and this API runs on http://localhost:8000.
#     The browser sees "different origins" → CORS would block the request.
#     This middleware tells the browser "it's ok, I allow that origin".
#
#   - In PRODUCTION: set FRONTEND_URL in your .env to your deployed frontend URL
#     e.g. FRONTEND_URL=https://my-app.web.app
#
# SECURITY: We only allow the specific FRONTEND_URL — not all origins.
# This prevents other websites from making API calls on behalf of your users.

allowed_origins = [
    FRONTEND_URL,
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_origin_regex=r"^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Health Check Endpoints ────────────────────────────────────────────────────
# These do NOT require authentication.
# Cloud Run uses health checks to know if the container is ready to serve traffic.

@app.get("/", tags=["Health"])
def root_health_check():
    """
    Root health check endpoint.
    Useful for confirming the server is running.
    """
    return {"status": "ok", "message": "Deep Research Agent API is running 🚀"}


@app.get("/health", tags=["Health"])
def health_check():
    """
    Health check endpoint (Cloud Run compatible).

    Cloud Run pings this to check if your container is alive.
    It MUST return 200 OK without requiring authentication.
    """
    return {"status": "ok"}


# ── Register Routes ───────────────────────────────────────────────────────────

# IMPORTANT: The history router MUST be registered BEFORE the research router.
# WHY? Both use the /research prefix. If research_router is registered first,
# then GET /research/history would be matched by GET /research/{research_id}
# (treating "history" as a research_id). Registering history first ensures
# the /history path is captured before the dynamic {research_id} path.

# Register history routes: GET /research/history and GET /research/{research_id}
app.include_router(history_router, prefix="/research", tags=["Research History"])

# Register the main research route: POST /research
app.include_router(research_router, prefix="/research", tags=["Research"])


# ── Server Startup ────────────────────────────────────────────────────────────

if __name__ == "__main__":
    # This block only runs when you execute: python main.py
    # uvicorn is the ASGI server that actually handles HTTP requests.

    # Cloud Run injects the PORT environment variable.
    # Locally, we default to 8000.
    port = int(os.environ.get("PORT", 8000))

    uvicorn.run(
        "main:app",       # "module:variable" — tells uvicorn where the app is
        host="0.0.0.0",   # Listen on ALL network interfaces (required for Docker/Cloud Run)
        port=port,        # Use PORT env var for Cloud Run compatibility
        reload=False,     # Set to True during development for auto-reload
    )
