import operator
from typing import List, TypedDict, Annotated, Literal, Optional, Dict, Any
from pydantic import BaseModel, Field
from langchain_core.messages import BaseMessage


class ChatState(TypedDict, total=False):
    # Original user question
    question: str
    task: Optional[str]

    # Tasks generated by planner
    research_tropics_planned: List[str]

    # Research findings from parallel researchers
    research_results: Annotated[List[str], operator.add]

    # Research collected/organized by collector
    collected_researchs: List[dict]

    # Critic QA review output
    critique: str

    # Final report generated by report writer
    final_report: str

    # Path of saved markdown report
    saved_file_path: str

    # Conversation/tool messages
    messages: Annotated[List[BaseMessage], operator.add]

    # Tracks whether web search was used
    web_search_performed: Annotated[bool, operator.or_]

    # Report containing [[IMAGE_1]], [[IMAGE_2]], etc.
    md_with_placeholders: str

    # Image generation specifications
    image_specs: List[dict]


class PlannerState(TypedDict):
    research_tasks: List[str]


class CriticState(BaseModel):
    is_sufficient: bool
    key_strengths: list[str]
    missing_gaps: list[str]
    feedback_for_writer: str
    overall_score: int = Field(ge=0, le=10)


class ImageSpec(BaseModel):
    placeholder: str = Field(..., description="e.g. [[IMAGE_1]]")
    filename: str = Field(..., description="Save under images/, e.g. architecture_flow.png")
    alt: str
    caption: str
    prompt: str = Field(..., description="Prompt to send to the image generation model.")
    size: Literal["1024x1024", "1024x1536", "1536x1024"] = "1024x1024"
    quality: Literal["low", "medium", "high"] = "medium"


class GlobalImagePlan(BaseModel):
    md_with_placeholders: str
    images: List[ImageSpec] = Field(default_factory=list)


class ImageSubgraphState(TypedDict, total=False):
    question: str
    final_report: str
    md_with_placeholders: str
    image_specs: List[dict]
